apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubenex
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AmanHogan/k3s-data-platform.git
    targetRevision: master
    path: manifests/kubenex
  destination:
    server: https://kubernetes.default.svc
    namespace: kubenex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
