apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracker
  namespace: tracker
  labels:
    app: tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracker
  template:
    metadata:
      labels:
        app: tracker
    spec:
      containers:
        - name: tracker
          image: 192.168.1.245:5001/tracker:5
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NEXTAUTH_URL
              value: "https://tracker.amanhogan.com"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: tracker-secrets
                  key: MONGODB_URI
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: tracker-secrets
                  key: NEXTAUTH_SECRET
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
