apiVersion: v1
kind: Namespace
metadata:
  name: portfolio
---
apiVersion: v1
kind: Namespace
metadata:
  name: data-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: cicd
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
